// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhRziP1Di4glf0TPGrAcpD6BFzzWpVNjw',
    appId: '1:837694977326:web:53ed0d8df6a109d66c36bf',
    messagingSenderId: '837694977326',
    projectId: 'projettodo-a9477',
    authDomain: 'projettodo-a9477.firebaseapp.com',
    storageBucket: 'projettodo-a9477.firebasestorage.app',
    measurementId: 'G-DNDCKWJP9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhgczqEsD5jBZ7MgofN4Vbh-nO1ibUo2A',
    appId: '1:837694977326:android:b942b740a834bad86c36bf',
    messagingSenderId: '837694977326',
    projectId: 'projettodo-a9477',
    storageBucket: 'projettodo-a9477.firebasestorage.app',
  );
}
